### ISSUE TITLE
⚠️ Information: Future card configuration changes.

### ISSUE THREAD

**Issue by thomasloven** [AmoebeLabs/flex-horseshoe-card#11]
Hi.

A change in how lovelace cards are set up in Home Assistant 0.105 increases performance, but enables cards to accidentally modify their own configuration in the loaded lovelace configuration.

I'm going through the cards in the HACS default repository, and noticed that your card may be susceptible to this. Looking through your code it seems you may modify parts of the config object passed to your card in `setConfig`.

The result could be that your card does not work well with the GUI editors or that parts of the configuration start showing up multiple times.

At some point in the future, it is likely that the configuration will be frozen before being passed to `setConfig`. At this point, your card will fail entirely when it tries to modify the configuration object.

There are several ways to fix/protect agains this problem.

The best is to restructure `setConfig` such that the configuration is never modified.
Other alternatives are to make a copy of the configuration and work on that instead.

```javascript
setConfig(config) {
  config = { ...config }; // This works for simple configurations not containing arrays or objects
...
```
```javascript
import { deepClone } from "deep-clone-simple";
// https://github.com/balloob/deep-clone-simple

setConfig(config) {
  config = deepClone(config); // This is a safe and fast method
...
```
or
```javascript
setConfig(config) {
  config = JSON.parse(JSON.stringify(config)); // This uses built-in functions, but may be slower than deepClone
  ...
```

Please note that I have not tested your card agains Home Assistant 0.105 or later, but just quickly looked through the code. If I'm mistaken in my assessment, I appologize for taking your time.

See thomasloven/hass-config#6 for more info.

**Comment by Lau-ie** [comment]
Confirmed broken in 106 with error:
Cannot add property tap_action, object is not extensible

**Comment by thomasloven** [comment]
A workaround might be to add
```yaml
tap_action:
  action: more-info
```
to *every* entity.

**Comment by Lau-ie** [comment]
Thank you! That works....

**Comment by Lau-ie** [comment]
I have take back my earlier comment. Seemd to be some caching going on in my browser which made it seem like it worked.

I've added the tap_Action to every entity but unfortunately it's still broken. The errormessage:
Cannot add property tap_action, object is not extensible
Is still in the console.

**Comment by Lau-ie** [comment]
I've made a pull request with a small modification to make the card 0.106.x compatible.

Confirmed working on my install, see branch: 0.106.x-compatibility

**Comment by genem2** [comment]
Not sure what my problem is, but I downloaded your .js file, as well as added that one line in the original file, after the setConfig(config) { line. Played with the ?v=999, nothing helps.  I'm also getting the following in the HA log:

[frontend.js.latest.202002205] <my_HA>/lovelace/system:0:0 Uncaught 

Just confirming: this is affecting all 106.x users, right?
Tnx

**Comment by Lau-ie** [comment]
Sorry to hear youy guys are still having problems. I'm currentlyu running Home Assistant 0.106.4 and have working horseshoes.

Only changes I made are the single modified line in the .js file and adding:
```
        tap_action:
          action: more-info
```
To every entity in the horseshoe config.

you could login in an incognito window/other browser to see if there really isn't a problem with any caching. But other then that I'm at a loss.....

**Comment by Lau-ie** [comment]
Some other users on the Community forum found the probable reason for it not working:

> UPDATE:
> Done!!! I made the change on flex-horseshoe-card.js, then deleted the flex-horseshoe-card.gz. If you don’t delete the gz file, browser still uses the gzipped version. After that i pressed Ctrl+F5 in firefox. Voila… everything works fine now… thanks a lot @PostNL…
