### ISSUE TITLE
Cannot read property 'setConfig' of undefined

### ISSUE THREAD

**Issue by LanceMcCarthy** [AmoebeLabs/flex-horseshoe-card#13]
I try not to open issues that skew towards support, but I've double checked that I followed the instructions before coming here.

### Error

When creating a simple "getting started" card, the following error is thrown:

![image](https://user-images.githubusercontent.com/3520532/75122065-0cd38e00-5668-11ea-802c-95524755c9b4.png)

I am running the latest version of Home Assistant `Home Assistant 0.105.5` on HassOS in a VM.

```
- type: 'custom:flex-horseshoe-card'
  entities:
    - entity: sensor.glances_ram_used
      icon: 'mdi:memory'
      name: RAM Usage
```

### Verifying Dependencies

I have restarted the Home Assistant Server several times since this was installed.

I can confirm the `sensor.glances_ram_used` entity itself exists and works, here a screenshot underneath another card using the same entity:

![image](https://user-images.githubusercontent.com/3520532/75121994-83bc5700-5667-11ea-8e72-7e9857495323.png)

I've double checked that the script source is being loaded at the top of the UI resources:

![image](https://user-images.githubusercontent.com/3520532/75122013-9df63500-5667-11ea-9c34-15e62024fa70.png)

Finally, I double checked that the file is where it is supposed to be:

![image](https://user-images.githubusercontent.com/3520532/75122038-d0079700-5667-11ea-8371-e68d215c0d11.png)

**Comment by mimarcos** [comment]
Get rid of the starting - and de-indent all the lines.

I think the examples are a little off. None of this worked for me and I had the same error until I removed the dash and left all the props top level.

**Comment by LanceMcCarthy** [comment]
@mimarcos Are you really sure you're still using Horseshoe card anymore? It sounds like you incidentally switched to a normal entities card.

**Comment by mimarcos** [comment]
Very certain I am. I hit the same issue as you. Did you even try this?

![Screen Shot 2020-07-31 at 7 34 36 AM](https://user-images.githubusercontent.com/625536/89031427-7edb8d80-d300-11ea-9305-df09c3958c0c.png)
![Screen Shot 2020-07-31 at 7 34 26 AM](https://user-images.githubusercontent.com/625536/89031418-797e4300-d300-11ea-87bc-c607c7f21745.png)
