### ISSUE TITLE
Card layout issue in App Home Assistant on Android tablet

### ISSUE THREAD

**Issue by VoetenK** [AmoebeLabs/flex-horseshoe-card#39]
I am using the flex horseshoe card on an Android tablet. When I open Home Assistant in Chrome, Firefox or Edge, the layout is correct. When I open Home assistant on my tablest with the App, the laytout is wrong. The problem is that the icons are placed incorrectly. The size of the icon is also larger. How can this be solved?
![Oke](https://user-images.githubusercontent.com/27051683/113574897-53423d00-961d-11eb-88c3-38555fb04f6c.png)
![NotOke](https://user-images.githubusercontent.com/27051683/113574928-60f7c280-961d-11eb-9c1b-6a2528d68252.png)

**Comment by 5ur3n** [comment]
Same here - the floating white thing in the bottom right of this screenshot is the "light" icon from the "one bulb" default example - ignore the "geyser", I intentionally removed the icons there.

I anticipate this might be a problem with the Home Assistant app rather than horseshoe card since the card renders fine in chrome on the android device.

![Screenshot_20210718-115415_Home Assistant](https://user-images.githubusercontent.com/46934892/126063007-d9168cf4-bda0-450f-b4d8-b05d39d756bf.jpg)

**Comment by Reinqusito** [comment]
Same here, on Android app not correctly aligned..
**xpos:** is with the same value of the circle.
`icons:
- id: 0
  animation_id: 0
  xpos: 50
  ypos: 75
   
circles:
- id: 0
  animation_id: 0
  xpos: 50
  ypos: 70
  radius: 35			  `
![b1](https://user-images.githubusercontent.com/82607551/131166152-18bd58fb-d08f-4fea-b29e-301a3a72b26f.jpg)
![b3](https://user-images.githubusercontent.com/82607551/131166170-1c175df1-5ad3-407e-8712-786988f51368.jpg)

**Comment by arboeh** [comment]
Similar behaviour for me, but mdi-icon is completely invisible for me in Home Assistant Companion:

Companion:
![Screenshot_20211011-081132](https://user-images.githubusercontent.com/12322114/136741732-c2c273b4-b308-49fe-b687-9b668a492184.png)

Chrome (Mobile / PC):
![2021-10-11 08_11_14-Window](https://user-images.githubusercontent.com/12322114/136741777-3d77b90c-ce97-4b71-8949-617efac21406.png)

Card-configuration: [card_02.txt](https://github.com/AmoebeLabs/flex-horseshoe-card/files/7319938/card_02.txt)

**Comment by arboeh** [comment]
Very good news: Working for me on Android since latest beta-1534-9f3f552 of Home Assistant Companion.

**Comment by spudje** [comment]
Still not working for me.  E.g. xpos & ypos of icon lpaces icon correctly in browsers, but it places the icon totally wrong in the Home Assistant Android app. I'm a bit surprised this is still the case after multiple years.

**Comment by AmoebeLabs** [comment]
> Still not working for me. E.g. xpos & ypos of icon lpaces icon correctly in browsers, but it places the icon totally wrong in the Home Assistant Android app. I'm a bit surprised this is still the case after multiple years.

Did you clear the frontend cache in the Companion App ?

And could you specify the Android & WebView version?

**Comment by spudje** [comment]
Apologies, I'm so sorry. Apparently v1.1 broke something and v1.2 fixed it again. My bad.

**Comment by AmoebeLabs** [comment]
> Apologies, I'm so sorry. Apparently v1.1 broke something and v1.2 fixed it again. My bad.

No worries. v1.1 did not contain the fix for Android. That was v1.2.

Now if that one works for you, I'm happy that I was able to fix that long standing bug!

**Comment by AmoebeLabs** [comment]
Closed. 
- See issue #67

That PR should have fixed this problem.
