### ISSUE TITLE
Layout: icons: size: 1.2 does not work on android tablet. 

### ISSUE THREAD

**Issue by VoetenK** [AmoebeLabs/flex-horseshoe-card#46]
I want to change the size of an icon according to the example.
             icons:
               # Icons 0 refers to the second entity in the list, ie index 1
               - id: 0
                 entity_index: 1
                 xpos: 37
                 ypos: 57
                 align: end
                 size: 1.3
This works fine on PC and iPhone.
This does not work on an android tablet.
What is the solution for this?

**Comment by AmoebeLabs** [comment]
Closed.
- Issue #67 fixes this

Released with version v1.2 of the card.
