### ISSUE TITLE
FR: Make value changes smoothly

### ISSUE THREAD

**Issue by VDRainer** [AmoebeLabs/flex-horseshoe-card#6]
It would be nice if the value of the horseshoe changes smoothly and don't jump to the next value.
Like in the [custom gauge card](https://github.com/custom-cards/gauge-card).
If you have sensors that change frequently fast, like from a solar system.

Thanks for this great card and your time.

**Comment by AmoebeLabs** [comment]
This is - well it should - already possible with the styling, but then you have to know exactly how that is done.

As it looks very nice, I can make it the default behavior, the same as the custom gauge does.

**Comment by AmoebeLabs** [comment]
Implemented in 0.8.3

**Comment by VDRainer** [comment]
That's pretty COOL!
Thanks alot!
