### ISSUE TITLE
Home Assistant 2023.2.5 - horseshoe-card

### ISSUE THREAD

**Issue by xmaxtclub** [AmoebeLabs/flex-horseshoe-card#61]
are they not compatible with the latest version of ha? after the update i can't see them anymore and i get error "Custom element doesn't exist: flex-horseshoe-card." thanks

**Comment by HAPSagan** [comment]
Same for me. 😢

**Comment by martinh12345** [comment]
i have the same, but i didn't update anything.

**Comment by martinh12345** [comment]
looks like there is a problem at : https://unpkg.com/

**Comment by martinh12345** [comment]
Failed to load resource: net::ERR_FAILED
:8123/lovelace/default_view:1 Access to script at 'https://unpkg.com/lit-html@%5E1.0.0/lib/shady-render?module' from origin 'http://homeassistant.local:8123' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
unpkg.com/lit-html@%5E1.0.0/lib/shady-render?module:1          Failed to load resource: net::ERR_FAILED

**Comment by plepola** [comment]
Same situation here; it doesn't work, unfortunately.

**Comment by HAPSagan** [comment]
I restored 2023.2.4 and now it works for me.

**Comment by jlc71710** [comment]
Same situation : Custom element doesn't exist: flex-horseshoe-card. after HA update

**Comment by plepola** [comment]
Now I booted my Home Assistant (2023.2.5), and the horseshoes work again, weird.

**Comment by jlc71710** [comment]
It's also ok for me : it come back after a time ... (I don't know if someone work on it but it's ok again)

**Comment by xmaxtclub** [comment]
I confirm, everything works again! top
