### ISSUE TITLE
Any update on the latest versions of HA working with your great card?

### ISSUE THREAD

**Issue by meteosat007** [AmoebeLabs/flex-horseshoe-card#68]
Hi,

I have downloaded the latest Develop .js file and then generated the .gz the file, loaded them into /config/www/communityflex-horseshoe-card/
However it still doesnt recognise the card.

Any thoughts on whats next to allow me and others to make use of your hard work and can I say stunning capability.

Alan

**Comment by AmoebeLabs** [comment]
Did you add the card into the resources part of Lovelace, either included as a file or directly?

If you use HACS, that one does it automatically for you.

**Comment by meteosat007** [comment]
Hi Marco.

I have tried via HACS then add resources from the correct /config/www/community/flex folder then the .js file.

Always states custom Card not found despite I can see the folder etc....


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by meteosat007** [comment]
Hi Marco,

 

I deleted everything, restarted then loaded again on the develop branch and today it works.

Did the same yesterday and nothing.

 

Look forward to using it in anger now and thanks again for a great card.

 

Alan

**Comment by AmoebeLabs** [comment]
Great!

Sometimes you have to restart HA to make it work. I have that sometimes with other custom cards. No idea why!
